# Generated by Django 3.0.4 on 2021-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
